# Generated by Django 4.2.1 on 2023-06-02 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter country', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter genre', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='enter title', max_length=200)),
                ('duration', models.DurationField(help_text='enter duration')),
                ('poster', models.ImageField(help_text='put the poster here', upload_to='')),
                ('description', models.TextField(help_text='enter description')),
                ('rating', models.FloatField(help_text='enter rating')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.country')),
                ('genre', models.ManyToManyField(help_text='select genre', to='catalog.genre')),
            ],
        ),
    ]
