# Generated by Django 4.2.1 on 2023-06-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_moviesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesession',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='moviesession',
            name='lounge_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='moviesession',
            name='time_begin',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='moviesession',
            name='time_end',
            field=models.TimeField(null=True),
        ),
    ]
