# Generated by Django 4.2.1 on 2023-06-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_movie_budget_alter_movie_year_of_production"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.ImageField(upload_to="static/catalog/posters/"),
        ),
    ]
