# Generated by Django 4.2.1 on 2023-06-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_alter_movie_poster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.ImageField(upload_to="static/catalog/posters/"),
        ),
    ]
